version: '3'
services:
  db:
    image: postgres:11
    container_name: postgres
    # postgresの環境変数
    env_file: ./env/env_postgres
    ports:
      - 5432:5432
    networks:
      - sample-network
    volumes:
      # 起動スクリプト
      - ./initdb:/docker-entrypoint-initdb.d
  app:
    image: openjdk:8-jdk-alpine
    depends_on:
      # dbが起動してからappを起動
      - db
    ports:
      - "8081:8081"
    networks:
      - sample-network
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    command: ./mvnw spring-boot:run
networks:
  sample-network:
    external: true